name: PushAction

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - .github/workflows/pullrequest.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Cancel previous runs
        uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: philips-software/sonar-scanner-action@master
        with:
          url: ${{ secrets.SONARQUBE_HOST }}
          token: ${{ secrets.SONARQUBE_TOKEN }}
          projectKey: github-action-scripts
          projectName: GitHub Action Scripts

      - name: Cleanup scan
        run: sudo rm -rf "$GITHUB_WORKSPACE/.scannerwork"
